"""Versioned configuration for embeddings produced during ingestion."""

from __future__ import annotations

import json
import os
import tomllib
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

VALID_EMBEDDINGS = frozenset({"text", "clap", "gemini", "yamnet"})
DEFAULT_EMBEDDINGS = ("text", "clap")


@dataclass(frozen=True)
class EmbeddingConfig:
    active: frozenset[str]
    text_model: str = "sentence-transformers/all-MiniLM-L6-v2"
    clap_model: str = "laion/clap-htsat-unfused"
    gemini_model: str = "gemini-embedding-2"
    gemini_output_dimensionality: int = 1536
    yamnet_model: str = "https://tfhub.dev/google/yamnet/1"
    yamnet_top_k: int = 5

    def is_active(self, embedding_name: str) -> bool:
        return embedding_name in self.active


def embedding_config_from_env(env: Mapping[str, str] | None = None) -> EmbeddingConfig:
    """Build the ingestion embedding configuration from environment variables."""
    values = os.environ if env is None else env
    raw_active = values.get("EMBEDDINGS_ACTIVE", ",".join(DEFAULT_EMBEDDINGS))
    active = frozenset(name.strip().lower() for name in raw_active.split(",") if name.strip())
    unsupported = active - VALID_EMBEDDINGS
    if unsupported:
        raise ValueError(f"Unsupported embeddings in EMBEDDINGS_ACTIVE: {sorted(unsupported)}")
    if not active:
        raise ValueError("EMBEDDINGS_ACTIVE must enable at least one embedding")

    try:
        gemini_dimensions = int(values.get("GEMINI_EMBEDDING_OUTPUT_DIMENSIONALITY", "1536"))
        yamnet_top_k = int(values.get("YAMNET_TOP_K", "5"))
    except ValueError as error:
        raise ValueError("Embedding numeric environment variables must be integers") from error
    if gemini_dimensions <= 0:
        raise ValueError("GEMINI_EMBEDDING_OUTPUT_DIMENSIONALITY must be a positive integer")
    if yamnet_top_k <= 0:
        raise ValueError("YAMNET_TOP_K must be a positive integer")

    return EmbeddingConfig(
        active=active,
        text_model=values.get("TEXT_EMBEDDING_MODEL", "sentence-transformers/all-MiniLM-L6-v2"),
        clap_model=values.get("CLAP_EMBEDDING_MODEL", "laion/clap-htsat-unfused"),
        gemini_model=values.get("GEMINI_EMBEDDING_MODEL", "gemini-embedding-2"),
        gemini_output_dimensionality=gemini_dimensions,
        yamnet_model=values.get("YAMNET_MODEL", "https://tfhub.dev/google/yamnet/1"),
        yamnet_top_k=yamnet_top_k,
    )


def write_embedding_config_from_env(
    path: str | Path, env: Mapping[str, str] | None = None
) -> EmbeddingConfig:
    """Generate the TOML artifact consumed by ingestion from the environment."""
    config = embedding_config_from_env(env)
    config_path = Path(path)
    config_path.parent.mkdir(parents=True, exist_ok=True)
    active = [name for name in ("text", "clap", "gemini", "yamnet") if name in config.active]
    config_path.write_text(
        "# Generated from .env; edit the EMBEDDINGS_* variables instead.\n"
        "# Do not edit this file manually: it is regenerated before each CLI ingestion run.\n"
        "[embeddings]\n"
        f"active = {json.dumps(active)}\n\n"
        "[embeddings.text]\n"
        f"model = {json.dumps(config.text_model)}\n\n"
        "[embeddings.clap]\n"
        f"model = {json.dumps(config.clap_model)}\n\n"
        "[embeddings.gemini]\n"
        f"model = {json.dumps(config.gemini_model)}\n"
        f"output_dimensionality = {config.gemini_output_dimensionality}\n\n"
        "[embeddings.yamnet]\n"
        f"model = {json.dumps(config.yamnet_model)}\n"
        f"top_k = {config.yamnet_top_k}\n",
        encoding="utf-8",
    )
    return config


def load_embedding_config(path: str | Path) -> EmbeddingConfig:
    """Load and validate the explicit list of embeddings to generate."""
    config_path = Path(path)
    if not config_path.exists():
        raise FileNotFoundError(f"Embedding configuration not found: {config_path}")
    raw = tomllib.loads(config_path.read_text())
    embeddings = raw.get("embeddings", {})
    active = frozenset(embeddings.get("active", []))
    unsupported = active - VALID_EMBEDDINGS
    if unsupported:
        raise ValueError(f"Unsupported embeddings in {config_path}: {sorted(unsupported)}")
    if not active:
        raise ValueError("embeddings.active must enable at least one embedding")

    text = embeddings.get("text", {})
    clap = embeddings.get("clap", {})
    gemini = embeddings.get("gemini", {})
    yamnet = embeddings.get("yamnet", {})
    dimensions = gemini.get("output_dimensionality", 1536)
    if not isinstance(dimensions, int) or dimensions <= 0:
        raise ValueError("embeddings.gemini.output_dimensionality must be a positive integer")
    yamnet_top_k = yamnet.get("top_k", 5)
    if not isinstance(yamnet_top_k, int) or yamnet_top_k <= 0:
        raise ValueError("embeddings.yamnet.top_k must be a positive integer")
    return EmbeddingConfig(
        active=active,
        text_model=text.get("model", "sentence-transformers/all-MiniLM-L6-v2"),
        clap_model=clap.get("model", "laion/clap-htsat-unfused"),
        gemini_model=gemini.get("model", "gemini-embedding-2"),
        gemini_output_dimensionality=dimensions,
        yamnet_model=yamnet.get("model", "https://tfhub.dev/google/yamnet/1"),
        yamnet_top_k=yamnet_top_k,
    )
