"""Configuration for retrieval embeddings and classifiers produced during ingestion."""

from __future__ import annotations

import json
import os
import tomllib
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

VALID_EMBEDDINGS = frozenset({"text", "clap", "gemini"})
VALID_CLASSIFIERS = frozenset({"yamnet"})
DEFAULT_EMBEDDINGS = ("text", "clap")
DEFAULT_CLASSIFIERS: tuple[str, ...] = ()


@dataclass(frozen=True)
class EmbeddingConfig:
    active_embeddings: frozenset[str]
    active_classifiers: frozenset[str] = frozenset()
    text_model: str = "sentence-transformers/all-MiniLM-L6-v2"
    clap_model: str = "laion/clap-htsat-unfused"
    gemini_model: str = "gemini-embedding-2"
    gemini_output_dimensionality: int = 1536
    yamnet_model: str = "https://tfhub.dev/google/yamnet/1"
    yamnet_top_k: int = 5

    def is_embedding_active(self, embedding_name: str) -> bool:
        return embedding_name in self.active_embeddings

    def is_classifier_active(self, classifier_name: str) -> bool:
        return classifier_name in self.active_classifiers


def _active_values(
    raw_value: str | list[object],
    *,
    valid: frozenset[str],
    setting: str,
    required: bool,
) -> frozenset[str]:
    values = (
        (name.strip().lower() for name in raw_value.split(","))
        if isinstance(raw_value, str)
        else (str(name).strip().lower() for name in raw_value)
    )
    active = frozenset(name for name in values if name)
    unsupported = active - valid
    if unsupported:
        raise ValueError(f"Unsupported entries in {setting}: {sorted(unsupported)}")
    if required and not active:
        raise ValueError(f"{setting} must enable at least one embedding")
    return active


def embedding_config_from_env(env: Mapping[str, str] | None = None) -> EmbeddingConfig:
    """Build the ingestion embedding configuration from environment variables."""
    values = os.environ if env is None else env
    raw_embeddings = values.get("EMBEDDINGS_ACTIVE", ",".join(DEFAULT_EMBEDDINGS))
    active_embeddings = _active_values(
        raw_embeddings,
        valid=VALID_EMBEDDINGS,
        setting="EMBEDDINGS_ACTIVE",
        required=True,
    )
    active_classifiers = _active_values(
        values.get("CLASSIFIERS_ACTIVE", ",".join(DEFAULT_CLASSIFIERS)),
        valid=VALID_CLASSIFIERS,
        setting="CLASSIFIERS_ACTIVE",
        required=False,
    )

    try:
        gemini_dimensions = int(values.get("GEMINI_EMBEDDING_OUTPUT_DIMENSIONALITY", "1536"))
        yamnet_top_k = int(values.get("YAMNET_TOP_K", "5"))
    except ValueError as error:
        raise ValueError("Embedding numeric environment variables must be integers") from error
    if gemini_dimensions <= 0:
        raise ValueError("GEMINI_EMBEDDING_OUTPUT_DIMENSIONALITY must be a positive integer")
    if yamnet_top_k <= 0:
        raise ValueError("YAMNET_TOP_K must be a positive integer")

    return EmbeddingConfig(
        active_embeddings=active_embeddings,
        active_classifiers=active_classifiers,
        text_model=values.get("TEXT_EMBEDDING_MODEL", "sentence-transformers/all-MiniLM-L6-v2"),
        clap_model=values.get("CLAP_EMBEDDING_MODEL", "laion/clap-htsat-unfused"),
        gemini_model=values.get("GEMINI_EMBEDDING_MODEL", "gemini-embedding-2"),
        gemini_output_dimensionality=gemini_dimensions,
        yamnet_model=values.get("YAMNET_MODEL", "https://tfhub.dev/google/yamnet/1"),
        yamnet_top_k=yamnet_top_k,
    )


def write_embedding_config_from_env(
    path: str | Path, env: Mapping[str, str] | None = None
) -> EmbeddingConfig:
    """Generate the TOML artifact consumed by ingestion from the environment."""
    config = embedding_config_from_env(env)
    config_path = Path(path)
    config_path.parent.mkdir(parents=True, exist_ok=True)
    active_embeddings = [
        name for name in ("text", "clap", "gemini") if name in config.active_embeddings
    ]
    active_classifiers = [
        name for name in ("yamnet",) if name in config.active_classifiers
    ]
    config_path.write_text(
        "# Generated from .env; edit EMBEDDINGS_ACTIVE and CLASSIFIERS_ACTIVE instead.\n"
        "# Do not edit this file manually: it is regenerated before each CLI ingestion run.\n"
        "[embeddings]\n"
        f"active = {json.dumps(active_embeddings)}\n\n"
        "[embeddings.text]\n"
        f"model = {json.dumps(config.text_model)}\n\n"
        "[embeddings.clap]\n"
        f"model = {json.dumps(config.clap_model)}\n\n"
        "[embeddings.gemini]\n"
        f"model = {json.dumps(config.gemini_model)}\n"
        f"output_dimensionality = {config.gemini_output_dimensionality}\n\n"
        "[classifiers]\n"
        f"active = {json.dumps(active_classifiers)}\n\n"
        "[classifiers.yamnet]\n"
        f"model = {json.dumps(config.yamnet_model)}\n"
        f"top_k = {config.yamnet_top_k}\n",
        encoding="utf-8",
    )
    return config


def load_embedding_config(path: str | Path) -> EmbeddingConfig:
    """Load and validate explicit embedding and classifier configuration."""
    config_path = Path(path)
    if not config_path.exists():
        raise FileNotFoundError(f"Embedding configuration not found: {config_path}")
    raw = tomllib.loads(config_path.read_text())
    embeddings = raw.get("embeddings", {})
    raw_embedding_active = embeddings.get("active", [])
    if not isinstance(raw_embedding_active, list):
        raise ValueError("embeddings.active must be a list")
    legacy_classifiers = frozenset(raw_embedding_active) & VALID_CLASSIFIERS
    active_embeddings = _active_values(
        [name for name in raw_embedding_active if name not in VALID_CLASSIFIERS],
        valid=VALID_EMBEDDINGS,
        setting="embeddings.active",
        required=True,
    )

    classifiers = raw.get("classifiers", {})
    if not isinstance(classifiers, dict):
        raise ValueError("classifiers must be a table")
    raw_classifier_active = classifiers.get("active", [])
    if not isinstance(raw_classifier_active, list):
        raise ValueError("classifiers.active must be a list")
    active_classifiers = _active_values(
        raw_classifier_active,
        valid=VALID_CLASSIFIERS,
        setting="classifiers.active",
        required=False,
    ) | legacy_classifiers

    text = embeddings.get("text", {})
    clap = embeddings.get("clap", {})
    gemini = embeddings.get("gemini", {})
    yamnet = classifiers.get("yamnet", embeddings.get("yamnet", {}))
    dimensions = gemini.get("output_dimensionality", 1536)
    if not isinstance(dimensions, int) or dimensions <= 0:
        raise ValueError("embeddings.gemini.output_dimensionality must be a positive integer")
    yamnet_top_k = yamnet.get("top_k", 5)
    if not isinstance(yamnet_top_k, int) or yamnet_top_k <= 0:
        raise ValueError("embeddings.yamnet.top_k must be a positive integer")
    return EmbeddingConfig(
        active_embeddings=active_embeddings,
        active_classifiers=active_classifiers,
        text_model=text.get("model", "sentence-transformers/all-MiniLM-L6-v2"),
        clap_model=clap.get("model", "laion/clap-htsat-unfused"),
        gemini_model=gemini.get("model", "gemini-embedding-2"),
        gemini_output_dimensionality=dimensions,
        yamnet_model=yamnet.get("model", "https://tfhub.dev/google/yamnet/1"),
        yamnet_top_k=yamnet_top_k,
    )
